OPTIONS = -std=c++11 -Wall

#
# UFRGS - Compiladores B - Marcelo Johann - 2009/2 - Etapa 1
#
# Makefile for two compiler calls
# The code generated by lex and main.c are separately compiled
# You must include lex.yy.h in your main as well as the definition of
# other interfaces like getLineNumber, initMe, running...
# Use make clean to remove old files before remaking everything
#

etapa1: lex.yy.o main.o
	g++ $(OPTIONS) -o etapa1 lex.yy.o main.o
%.o: %.cpp
	g++ $(OPTIONS) $< -c
lex.yy.cpp: scanner.l
	flex -o lex.yy.cpp --header-file=lex.yy.h scanner.l 
clean:
	rm *.o lex.yy.cpp etapa1
	rm lex.yy.h